name: amplab_essentia
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - scikit-learn
  - pip
  - pip:
      - tensorflow==2.8.0
      - essentia-tensorflow
      - streamlit
